### ISSUE TITLE
Local storage exceeded quota

### ISSUE THREAD

**Issue by Demoli** [sdinteractive/SomethingDigital_RecentlyViewed#8]
We are experiencing an issue with the JS local storage in `skin/frontend/base/default/js/sd_recentlyviewed/recent.js`, line 25.

Occasionally this is raising an exception `QuotaExceededError: An attempt was made to add something to storage that exceed the quota`

**Comment by mpchadwick** [comment]
[Seems to be related to private browsing mode in Safari](http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st). Can you confirm that that is where you are experiencing this?
